import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int input = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
	
		double birth = generator.nextDouble();
		boolean girlBorn = false;
		boolean boyBorn = false;
		int childCounter = 0;
		int girlCounter = 0;
		int boyCounter = 0;
		double twoKids = 0;
		double threeKids = 0;
		double manyKids = 0;
		for (int inputCounter = 0; inputCounter < input; inputCounter++){
			while (boyBorn == false || girlBorn == false){
				if (birth < 0.5){
					girlBorn = true; 
					birth = Math.random();
					childCounter++;
					girlCounter++;
				} else {
					boyBorn = true; 
					birth = Math.random();
					childCounter++;
					boyCounter++;
				} 
			}
			if (boyCounter + girlCounter == 2) {twoKids++;}
			if (boyCounter + girlCounter == 3) {threeKids++;}
			if (boyCounter + girlCounter > 3) {manyKids++;}
			boyCounter = 0;
			girlCounter = 0;
			boyBorn = false;
			girlBorn = false;
		}
		double average = (twoKids + threeKids + manyKids) / 3;
		System.out.println("Average: " + average + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + (int)twoKids);
		System.out.println("Number of families with 3 children: " + (int)threeKids);
		System.out.println("Number of families with 4 or more children: " + (int)manyKids);
		double mode;
		if (twoKids > threeKids && twoKids > manyKids){mode = (int)twoKids;}
		else if (threeKids > twoKids && threeKids > manyKids){mode = (int)threeKids;}
		else {mode = (int)manyKids;};

		System.out.println("The most common number of children is " + (int)mode);
	}
}