import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments

		int input = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		Random generator = new Random(seed);
		double birth = generator.nextDouble();
		boolean girlBorn = false;
		boolean boyBorn = false;
		int childCounter = 0;
		int girlCounter = 0;
		int boyCounter = 0;
		double twoKids = 0;
		double threeKids = 0;
		double manyKids = 0;
		for (int inputCounter = 0; inputCounter < input; inputCounter++){
			while (boyBorn == false || girlBorn == false){
				if (birth < 0.5){
					girlBorn = true; 
					girlCounter++;
				} else {
					boyBorn = true; 
					boyCounter++;
				} 
				birth = generator.nextDouble();
				childCounter++;
			}
			if (boyCounter + girlCounter == 2) {twoKids++;}
			if (boyCounter + girlCounter == 3) {threeKids++;}
			if (boyCounter + girlCounter > 3) {manyKids++;}
			boyCounter = 0;
			girlCounter = 0;
			boyBorn = false;
			girlBorn = false;
		}
		//System.out.println(twoKids);
		//System.out.println(threeKids);
		//System.out.println(manyKids);
		double average = (childCounter) / ((double) input);
		System.out.println("Average: " + average + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + (int)twoKids);
		System.out.println("Number of families with 3 children: " + (int)threeKids);
		System.out.println("Number of families with 4 or more children: " + (int)manyKids);
		String mode;
		if (twoKids > threeKids && twoKids > manyKids){mode = "2";}
		else if (threeKids > twoKids && threeKids > manyKids){mode = "3";}
		else {mode = "4 or more";};

		System.out.println("The most common number of children is " + mode + ".");
	}
}